# Generated by Django 4.2.7 on 2024-11-13 09:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='declaration',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 13, 9, 25, 37, 970383, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
        ),
    ]
