# Generated by Django 4.2.7 on 2024-12-11 01:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='declaration',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 11, 1, 29, 7, 861997, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
        ),
    ]
