# Generated by Django 4.2.7 on 2024-12-11 07:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_declaration_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='declaration',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 11, 7, 54, 49, 105802, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
        ),
    ]
